/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false apps/worker/src/worker-configuration.d.ts` (hash: a58031f6d278c7272b5edce742db99a2)
interface __BaseEnv_Env {
  DB: D1Database;
  PUBLIC_RATE_LIMITER: RateLimit;
  MUTATION_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
  ROADMAP_PUBLIC_URL: "https://roadmap.sakuracord.app";
  ROADMAP_ALLOWED_ORIGINS: "https://roadmap.sakuracord.app";
  ROADMAP_GATEWAY_PROVIDER: "cloudflare";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
