/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 89191f2ac71c563b027edf3bdd1a2e77)
interface __BaseEnv_Env {
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	JOBS: Queue;
	PUBLIC_RATE_LIMITER: RateLimit;
	REPORT_RATE_LIMITER: RateLimit;
	AI: Ai;
	WEBSITE_URL: "https://sakuracord.app";
	HUB_URL: "https://roadmap.sakuracord.app";
	TRIAGE_MODEL: "gpt-6-luna";
	TRIAGE_REASONING_EFFORT: "medium";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBSITE_URL" | "HUB_URL" | "TRIAGE_MODEL" | "TRIAGE_REASONING_EFFORT">> {}
}
